# This is a basic workflow to help you get started with Actions

name: automatic deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      #- name: Deploy to Staging server
      #  uses: easingthemes/ssh-deploy@v2.1.5
      #  env:
      #    SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #    #ARGS: "-rltgoDzvO" 
      #    SOURCE: ""
      #    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #    REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #    TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 22
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          scp_source: index.php favicon.png includes inc images e assets
          scp_target: ~/html/webshop
